- .scala-steward.conf
- build.sbt
- grid-layout-demo/vite.config.js
Replays https://github.com/gemini-hlsw/lucuma-react/pull/5
> Auto-generate vite config for demos

- .mergify.yml
- build.sbt
- clipboard/src/main/scala/react/clipboard/CopyToClipboard.scala
- clipboard/src/main/scala/react/clipboard/package.scala
- clipboard/src/test/scala/react/clipboard/CopyToClipboardSuite.scala
- clipboard/src/webpack/test.webpack.config.js
- clipboard/yarn.lock
- grid-layout/yarn.lock
- package.json
- test/yarn.lock
- yarn.lock
Replays https://github.com/gemini-hlsw/lucuma-react/pull/10
> Import clipboard

- build.sbt
Replays https://github.com/gemini-hlsw/lucuma-react/pull/15
> Name all the modules

- cats/src/main/scala/react/common/implicits/package.scala
- cats/src/test/scala/react/common/implicits/ReactCatsSuite.scala
- virtuoso-demo/src/main/scala/react/table/demo/Demo.scala
This merges in all the latest upstream changes, except grid-layout which seems to have had more extensive changes and I will PR separately.
> Merge upstream updates

- resize-detector/src/main/scala/react/resizeDetector/hooks.scala
https://github.com/gemini-hlsw/lucuma-ui/commit/c649a1f5f24cf43befd72efe4a41bb30f8576bac
> Cherry-pick "react-resize-detector needs to be import as js.Object "

- semantic-ui/src/main/scala/react/semanticui/collections/form/FormInput.scala
Notably https://github.com/cquiroz/scalajs-react-semantic-ui/pull/359.
> Merge in upstream SUI

- common/src/main/scala/react/common/enumValue.scala
- common/src/main/scala/react/common/syntax/package.scala
- font-awesome/src/main/scala/react/fa/FontAwesomeIcon.scala
- resizable/src/main/scala/react/resizable/Resizable.scala
- semantic-ui-demo/src/main/scala/react/semanticui/demo/elements/IconsComponent.scala
- semantic-ui/src/main/scala/react/semanticui/collections/form/FormGroup.scala
- semantic-ui/src/main/scala/react/semanticui/collections/grid/GridRow.scala
- semantic-ui/src/main/scala/react/semanticui/modules/popup/Popup.scala
The syntax extension is kind of a mess. I'll try to simplify it a bit
> Convert enum syntax

- tanstack-table-demo/src/main/scala/react/table/demo/Table1.scala
- tanstack-table-demo/src/main/scala/react/table/demo/Table2.scala
- tanstack-table-demo/src/main/scala/react/table/demo/Table3.scala
- tanstack-table/src/main/scala/lucuma/react/table/BuiltInSorting.scala
- tanstack-table/src/main/scala/lucuma/react/table/ColumnDef.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
- tanstack-table/src/main/scala/lucuma/react/table/TableOptions.scala
- tanstack-table/src/main/scala/lucuma/react/table/facade/ColumnDefJS.scala
- tanstack-table/src/main/scala/lucuma/react/table/facade/TableOptionsJS.scala
- tanstack-table/src/main/scala/lucuma/react/table/package.scala
- tanstack-table/src/main/scala/lucuma/react/table/props.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/HooksApiExt.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/VirtualHook.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/VirtualOptions.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/facade/VirtualOptionsJS.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/facade/Virtualizer.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/package.scala
Flesh out react-table and react-virtual facades, plus a standard HTML renderer.
> Table + Virtual facades

- prime-react-demo/src/main/scala/react/table/demo/DemoComponents.scala
- prime-react/src/main/scala/react/primereact/Button.scala
- prime-react/src/main/scala/react/primereact/Message.scala
- prime-react/src/main/scala/react/primereact/ProgressSpinner.scala
- prime-react/src/main/scala/react/primereact/SelectItem.scala
- prime-react/src/main/scala/react/primereact/ToggleButton.scala
- prime-react/src/main/scala/react/primereact/TooltipOptions.scala
Also very minor changes and our own facade for TooltipOptions.
> Add facades for PrimeReact's ToggleButton, Message, ProgressSpinner

- build.sbt
- prime-react-demo/src/main/scala/react/table/demo/DemoComponents.scala
- prime-react/package.json
- prime-react/src/main/scala/react/primereact/Message.scala
- prime-react/src/main/scala/react/primereact/MessageItem.scala
- prime-react/src/main/scala/react/primereact/Messages.scala
- prime-react/src/main/scala/react/primereact/PrimeStyles.scala
- prime-react/src/main/scala/react/primereact/hooks/UseMessagesRef.scala
- prime-react/src/main/scala/react/primereact/hooks/hooks.scala
- prime-react/yarn.lock
I didn't end up using `Messages` but maybe it will be useful in the future.
Also, it appears that dependabot doesn't update the module specific package files, so I updated primereact to the latest version. It has already been updated in the root file.
> Add Messages component. Also add class to Message icon for spacing

- build.sbt
- prime-react/src/main/scala/react/primereact/Button.scala
- prime-react/src/main/scala/react/primereact/ConfirmPopup.scala
- prime-react/src/main/scala/react/primereact/Image.scala
- prime-react/src/main/scala/react/primereact/MenuItem.scala
- prime-react/src/main/scala/react/primereact/Message.scala
- prime-react/src/main/scala/react/primereact/MessageItem.scala
- prime-react/src/main/scala/react/primereact/PopupTieredMenu.scala
- prime-react/src/main/scala/react/primereact/Tag.scala
- prime-react/src/main/scala/react/primereact/ToggleButton.scala
- prime-react/src/main/scala/react/primereact/primereact.scala
Also allows use of Image as icons in components.
> Add PopupTieredMenu and Image to primereact

- build.sbt
- prime-react-demo/src/main/scala/react/table/demo/DemoControlsPanel.scala
- prime-react/src/main/scala/react/primereact/DropdownBase.scala
- prime-react/src/main/scala/react/primereact/MultiSelect.scala
- prime-react/src/main/scala/react/primereact/SelectItem.scala
- prime-react/src/main/scala/react/primereact/SelectItemGroup.scala
- prime-react/src/main/scala/react/primereact/primereact.scala
We will probably need the commented out options, as well as groups, which will require some additional modelling.
But this is a working start.
> MultiSelect

- build.sbt
- prime-react-demo/src/main/scala/react/table/demo/DemoComponents.scala
- prime-react-demo/src/main/scala/react/table/demo/TreeDemo.scala
- prime-react/src/main/scala/react/primereact/Button.scala
- prime-react/src/main/scala/react/primereact/ConfirmPopup.scala
- prime-react/src/main/scala/react/primereact/MenuItem.scala
- prime-react/src/main/scala/react/primereact/Message.scala
- prime-react/src/main/scala/react/primereact/MessageItem.scala
- prime-react/src/main/scala/react/primereact/PrimeStyles.scala
- prime-react/src/main/scala/react/primereact/Tag.scala
- prime-react/src/main/scala/react/primereact/ToggleButton.scala
- prime-react/src/main/scala/react/primereact/Tree.scala
- prime-react/src/main/scala/react/primereact/primereact.scala
Not all bindings are added, but we can add them as we go. Also see https://primereact.org/tree/
> Add primereact Tree bindings

- build.sbt
- prime-react/src/main/scala/react/primereact/PrimeStyles.scala
We need these for styling labels to look like buttons, etc.
> More PrimeStyles CSS classes.

- .github/workflows/ci.yml
- build.sbt
- prime-react-demo/src/main/scala/react/table/demo/TreeDemo.scala
- prime-react/src/main/scala/react/primereact/Tree.scala
Technically a breaking change, but as it's not used yet anywhere it should be fine
> Use Set[Tree.Id] for tree control

- .github/workflows/ci.yml
- .mergify.yml
- build.sbt
- markdown/src/main/scala/react/markdown/ReactMarkdown.scala
- package-lock.json
- package.json
> Add ReactMarkdown facade

- package-lock.json
- prime-react-demo/src/main/scala/lucuma/react/table/demo/DemoComponents.scala
- prime-react/src/main/scala/lucuma/react/primereact/Messages.scala
- prime-react/src/main/scala/lucuma/react/primereact/Toast.scala
`remove` on Message and Toast was not working on prime-react. It has now been fixed but it takes only one message at a time.
Added demo for this too.
> Fix remove on toast and implement on messages

- highcharts/src/main/scala/lucuma/react/highcharts/Chart.scala
Untested, that's why it's draft.
> Fix to chart race condition

- .scalafix.conf
- README.md
- beautiful-dnd-demo/vite.config.js
- build.sbt
- common/src/main/scala/lucuma/react/common/scalaComponents.scala
- datepicker-demo/vite.config.js
- floatingui/src/main/scala/lucuma/react/floatingui/package.scala
- font-awesome-demo/vite.config.js
- grid-layout-demo/vite.config.js
- highcharts-demo/vite.config.js
- hotkeys-demo/vite.config.js
- prime-react-demo/src/main/scala/lucuma/react/table/demo/Demo.scala
- prime-react-demo/vite.config.js
- resizable-demo/vite.config.js
- resize-detector-demo/src/main/scala/lucuma/react/resizeDetector/demo/Demo.scala
- resize-detector-demo/vite.config.js
- tanstack-table-demo/src/main/scala/lucuma/react/table/demo/Demo.scala
- tanstack-table-demo/vite.config.js
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/PartialTableState.scala
- tanstack-table/src/main/scala/lucuma/react/table/TableState.scala
For compatibility reasons I also had to update scala to 3.5.2, which has improved warnings. So, unused imports needed to be removed, and some extension methods as well.
> Update lucuma-react to 0.7.0

- build.sbt
- floatingui/src/main/scala/lucuma/react/floatingui/hooks.scala
- hotkeys-hooks/src/main/scala/lucuma/react/hotkeys/hooks.scala
- hotkeys-hooks/src/main/scala/lucuma/react/hotkeys/package.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/UseMessagesRef.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/UseOverlayPanelRef.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/UsePopupMenuRef.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/UseToastRef.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/hooks.scala
- resize-detector/src/main/scala/lucuma/react/resizeDetector/hooks.scala
- tanstack-table/src/main/scala/lucuma/react/table/TableHook.scala
- tanstack-table/src/main/scala/lucuma/react/table/package.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/VirtualHook.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/package.scala
This enables usage of the hooks in monadic style.
> Migrate hooks to monadic style

- prime-react-demo/src/main/scala/lucuma/react/table/demo/Demo.scala
- prime-react-demo/src/main/scala/lucuma/react/table/demo/DemoComponents.scala
- prime-react-demo/src/main/scala/lucuma/react/table/demo/DemoHooks.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/UseStorage.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/useDebounce.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/useInterval.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/useLocalStorage.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/useSessionStorage.scala
- prime-react/src/main/scala/lucuma/react/primereact/hooks/useTimeout.scala
I've implemented the ones I think we are most likely use. We can implement others as needed.
> Facades for some PrimeReact hooks
