- semantic-ui/src/main/scala/react/semanticui/addons/textarea/TextArea.scala
- semantic-ui/src/main/scala/react/semanticui/collections/form/FormTextArea.scala
- semantic-ui/src/main/scala/react/semanticui/foreachUnchecked.scala
The idea is to inline-and-reduce away the cast to `Nothing`. Bytecode analysis suggests it works.
> Try fixing `foreachUnchecked` with beta-reduce macro

- semantic-ui-demo/src/main/scala/react/semanticui/demo/elements/IconsComponent.scala
- semantic-ui-demo/src/main/scala/react/semanticui/demo/elements/LabelsComponent.scala
- semantic-ui/src/main/scala/react/semanticui/elements/header/Header.scala
- semantic-ui/src/main/scala/react/semanticui/elements/label/LabelDetail.scala
- semantic-ui/src/main/scala/react/semanticui/package.scala
- semantic-ui/src/test/scala/react/semanticui/collections/menu/MenuHeaderSuite.scala
- semantic-ui/src/test/scala/react/semanticui/collections/menu/MenuItemSuite.scala
- semantic-ui/src/test/scala/react/semanticui/collections/menu/MenuMenuSuite.scala
- semantic-ui/src/test/scala/react/semanticui/collections/menu/MenuSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/container/ContainerSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/divider/DividerSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/flag/FlagSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/header/HeaderContentSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/header/HeaderSubheaderSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/header/HeaderSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/image/ImageSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/list/ListContentSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/list/ListDescriptionSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/list/ListHeaderSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/list/ListItemSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/list/ListListSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/list/ListSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/loader/LoaderSuite.scala
- semantic-ui/src/test/scala/react/semanticui/elements/placeholder/PlaceholderSuite.scala
- Reposition `tagOf2AsC` to enable `as = <.tag` without further imports.
- Move `content` as first parameter (only in `Header` and `LabelDetail` for the moment):
In Scala 2 we were otherwise able to write `LabelDetail("hello")` which would invoke `LabelDetail.apply(modifiers: TagMod*)`. However, in Scala 3, the default `case class` constructor is called instead since it accepts a `String` as its first parameter, which was `as`. Therefore, invoking `LabelDetail("hello")` would result in the app attempting to render a `<hello>` tag.
The way I find around this is to move the `content` parameter to first place. Usually when specifying other parameters we name them all, and when we only specify a single unnamed parameter we usually mean the `content` parameter.
I'm not sure it's worth keeping …
> Minor fixes.

- build.sbt
... by layering an in-place find/replace on top of ST source generation 😩 
```diff
- @JSImport("primereact/badge/badge", "Badge")
+ @JSImport("primereact/badge/badge.esm", "Badge")
```
> Use ESM primereact sources in `JSImport`s

- build.sbt
One more fix for the regex used in the stImport rewrite for the JSImports in primereact.
The other regular expression `did` fail to match if the last 4 characters of the import were `.esm`. However, it also always excluded the last 4 characters of the import from the match group. It just so happened that I was looking at `Tag.scala` when I was checking to make sure additional `.esm` strings weren't appended to the import on each compile cycle. So,
`primereact/tag/tag` became `primereact/tag.esm` and didn't change with subsequent compiles. I didn't notice that one directory level had been dropped. But, `primereact/button/button` became `primereact/button/bu.esm`. 😆 
I switched the regex to use a negative lookbehind for the `.esm` and it seems to be working correctly now.
> Fix the regex in the prime-react/stImport rewrite

- build.sbt
- tanstack-table-demo/src/main/scala/react/table/demo/Table2.scala
- tanstack-table-demo/src/main/scala/react/table/demo/Table3.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
- tanstack-table/src/main/scala/lucuma/react/table/props.scala
Exposes a few commonly used virtualized options in the new virtualized table. Forces clients to specify a row height estimate.
> Expose some virtualized options in tables

- prime-react-demo/src/main/scala/react/table/demo/DemoComponents.scala
- prime-react/src/main/scala/react/primereact/TabPanel.scala
- prime-react/src/main/scala/react/primereact/TabView.scala
There is still some un-facaded functionality for preventing changing/closing of tabs. These were not included in the ST facade for some reason. 
But, I think this covers everything Raul is using in Observe.
> Add TabView/TabPanel primereact components

- build.sbt
- font-awesome/src/main/scala/react/fa/FontAwesomeIcon.scala
- prime-react/src/main/scala/react/primereact/primereact.scala
I think this is the behavior we'd more frequently desire. But, I could add a `addClass` method instead.
Right now, the primereact facade is adding a class to the icons in buttons, etc. That is removing the color class for the Trash icon.
> FontAwesomeIcon.clazz() adds a class rather than overwrites

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
- tanstack-table/src/main/scala/lucuma/react/virtual/package.scala
This PR fixes the issue described in https://app.shortcut.com/lucuma/story/1771/configuration-table-misbehavior#activity-1781.
Virtualized tables render a dummy padding in order to trick the scrollbar into thinking there are more rows. This padding is always outside of the range seen by the user.
However, the new virtualizer seems to get confused in some cases when the number of rows changes on the fly and renders less rows than it should. This resulted not only in missing rows but the padding being shown. We are using a beta version of the virtualizer after all.
This PR attempts to fix this by using a key in the virtualized table that changes when the number of rows change. This forces a rerender if the number of rows change and avoids the bug.
Additionally, it adds some debug info if …
> Force virtualized table rerender when number of rows changes

- beautiful-dnd/yarn.lock
- build.sbt
- circular-progressbar/yarn.lock
- clipboard/yarn.lock
- datepicker/yarn.lock
- draggable/yarn.lock
- floatingui/yarn.lock
- grid-layout/yarn.lock
- highcharts/yarn.lock
- hotkeys/yarn.lock
- moon/yarn.lock
- package.json
- prime-react/yarn.lock
- resizable/yarn.lock
- semantic-ui/yarn.lock
- tanstack-table/package.json
- tanstack-table/src/main/scala/lucuma/react/SizePx.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
- tanstack-table/src/main/scala/lucuma/react/table/PartialTableState.scala
- tanstack-table/src/main/scala/lucuma/react/table/TableOptions.scala
- tanstack-table/src/main/scala/lucuma/react/table/facade/TableOptionsJS.scala
- tanstack-table/src/main/scala/lucuma/react/table/props.scala
- tanstack-table/yarn.lock
- test/yarn.lock
- tree/yarn.lock
- yarn.lock
- Ability to keep (partial) table state externally.
- Ability to pass our own ref to the virtualized container. Useful if we use other functionality on the same `div`, like `resizeDetector`.
- Scala-idiomatic API on `TableOptions`.
> More additions to table facade

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
- tanstack-table/src/main/scala/lucuma/react/table/props.scala
Allows definition of a component to be shown, optionally, after table rows.
> Table subcomponents

- build.sbt
- prime-react-demo/src/main/scala/react/table/demo/DemoControlsPanel.scala
- prime-react/src/main/scala/react/primereact/Checkbox.scala
- prime-react/src/main/scala/react/primereact/Dropdown.scala
- prime-react/src/main/scala/react/primereact/DropdownBase.scala
- prime-react/src/main/scala/react/primereact/DropdownOptional.scala
- prime-react/src/main/scala/react/primereact/InputSwitch.scala
- prime-react/src/main/scala/react/primereact/InputText.scala
- prime-react/src/main/scala/react/primereact/InputTextarea.scala
- prime-react/src/main/scala/react/primereact/PrimeStyles.scala
- prime-react/src/main/scala/react/primereact/RadioButton.scala
- prime-react/src/main/scala/react/primereact/SelectButton.scala
- prime-react/src/main/scala/react/primereact/SelectButtonBase.scala
- prime-react/src/main/scala/react/primereact/SelectButtonMultiple.scala
- prime-react/src/main/scala/react/primereact/SelectButtonOptional.scala
This also adds an `onChangeE` event to the Dropdowns. I ended up not needing it, but left it because it could be useful. If someone feels it should be removed, I can pull it out.
> Add tooltips to more primereact components

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
When the empty message for an prime html table was displayed, react-devtools would display a big, red `ValidateDomNesting` warning like
> Text nodes cannot appear as a child of \<tr>.
or
> \<div> cannot appear as a child of `<tr>
depending on the  value of the emptyMessage.
> Fix table `emptyMessage`

- beautiful-dnd/yarn.lock
- circular-progressbar/yarn.lock
- clipboard/yarn.lock
- datepicker/yarn.lock
- draggable/yarn.lock
- floatingui/yarn.lock
- grid-layout/yarn.lock
- highcharts/yarn.lock
- hotkeys/yarn.lock
- moon/yarn.lock
- package.json
- prime-react/yarn.lock
- resizable/yarn.lock
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/props.scala
- tanstack-table/yarn.lock
- test/yarn.lock
- tree/yarn.lock
- yarn.lock
This allows passing a `Ref.To[HTMLElement]` to tables and virtualizers, like the one we get from `useResizeDetector`, instead of requiring `Ref.To[HTMLDivElement]`.
> Allow using more general refs in tables

- tanstack-table/src/main/scala/lucuma/react/syntax/package.scala
Allows you to use `^.height := 18.toPx`
> Add a `ValueType` vdomAttr for `SizePx`

- build.sbt
- grid-layout/src/main/scala/react/gridlayout/BaseProps.scala
- grid-layout/src/main/scala/react/gridlayout/ReactGridLayout.scala
- grid-layout/src/main/scala/react/gridlayout/ResponsiveReactGridLayout.scala
- grid-layout/src/main/scala/react/gridlayout/package.scala
- grid-layout/src/main/scala/react/gridlayout/raw/package.scala
Changing the type of `cols` did not fix the problem in Explore, but needed to be fixed anyway. 
`Layout.asList` is needed for merging the layouts in Explore.
Also make `LayoutItem.i` mandatory - it is mandatory in the typescript.
> Fix cols in rgl facade, add Layout.asList

- build.sbt
- font-awesome/src/main/scala/lucuma/react/fa/LayeredIcon.scala
- font-awesome/src/main/scala/lucuma/react/fa/TextLayer.scala
This PR provides more type safety on layered icon's children and allows calling `with*` methods on a `LayeredIcon` since children rendering is resolved at render time instead of definition.
> Better layered icons types

- build.sbt
- prime-react-demo/src/main/scala/lucuma/react/table/demo/TreeDemo.scala
- prime-react/src/main/scala/lucuma/react/primereact/Tree.scala
Uses a custom event instead of the original to make it easier to use
Depends on https://github.com/primefaces/primereact/pull/5081 as it expects the `data` field to be unchanged
> Add drag'n'drop facade for primereact/tree

- prime-react-demo/src/main/scala/lucuma/react/table/demo/DemoControlsPanel.scala
- prime-react/src/main/scala/lucuma/react/primereact/InputGroup.scala
Although documented as a component (https://primereact.org/inputgroup/), `InputGroup` is actually a `<div>` with a certain Prime class.
This PR implements it as an actual component so that we don't have to reference specific Prime classes in final code.
> Implement InputGroup

- common/src/main/scala/lucuma/react/common/givens/package.scala
- common/src/main/scala/lucuma/react/common/jsComponents.scala
- common/src/main/scala/lucuma/react/common/package.scala
- common/src/main/scala/lucuma/react/common/scalaComponents.scala
- common/src/main/scala/lucuma/react/common/size.scala
- common/src/main/scala/lucuma/react/common/style/package.scala
- common/src/main/scala/lucuma/react/common/syntax/package.scala
- common/src/test/scala/lucuma/react/common/arb/ArbSize.scala
- common/src/test/scala/lucuma/react/common/arb/ArbStyle.scala
- common/src/test/scala/lucuma/react/common/arb/package.scala
- common/src/test/scala/lucuma/react/common/givens/ReactCatsSuite.scala
- draggable/src/main/scala/lucuma/react/draggable/Draggable.scala
- draggable/src/main/scala/lucuma/react/draggable/package.scala
- floatingui/src/main/scala/lucuma/react/floatingui/package.scala
- floatingui/src/main/scala/lucuma/react/floatingui/syntax.scala
- floatingui/src/test/scala/react/floatingui/TooltipSuite.scala
- grid-layout-demo/src/main/scala/lucuma/react/gridlayout/Demo.scala
- grid-layout/src/main/scala/lucuma/react/gridlayout/BaseProps.scala
- grid-layout/src/test/scala/react/gridlayout/PackageTests.scala
- resize-detector/src/main/scala/lucuma/react/resizeDetector/ResizeDetector.scala
- resize-detector/src/main/scala/lucuma/react/resizeDetector/hooks.scala
- test/src/main/scala/lucuma/react/common/TestUtils.scala
- test/src/test/scala/react/common/CommonSuite.scala
- test/src/test/scala/react/common/ReactFnPropsSuite.scala
- test/src/test/scala/react/common/ReactFnPropsWithChildrenSuite.scala
- test/src/test/scala/react/common/ReactPropsForwardRefSuite.scala
- test/src/test/scala/react/common/ReactPropsForwardRefWithChildrenSuite.scala
- test/src/test/scala/react/common/ReactPropsSuite.scala
- test/src/test/scala/react/common/ReactPropsWithChildrenSuite.scala
- test/src/test/scala/react/common/StyleSuite.scala
Modernize `common` code to Scala 3 syntax, with better redistribution of givens.
Only new functionality is `Renderable` instances for `React[Fn]Props*`, introduced in `scalajs-react` 2.2.0.
> Modernize react-common, Renderable instances

- resize-detector/src/main/scala/lucuma/react/resizeDetector/ResizeDetector.scala
- resize-detector/src/main/scala/lucuma/react/resizeDetector/hooks.scala
This more closely resembles the original TS definitions: https://github.com/maslianok/react-resize-detector/blob/master/src/types.ts#L10
> Handle case where onResize x or y is undefined

- build.sbt
- common/src/main/scala/lucuma/react/common/scalaComponents.scala
- prime-react/src/main/scala/lucuma/react/primereact/InputNumber.scala
- prime-react/src/main/scala/lucuma/react/primereact/Tree.scala
- resize-detector-demo/src/main/scala/lucuma/react/resizeDetector/demo/HookDemo.scala
- resize-detector/src/main/scala/lucuma/react/resizeDetector/hooks.scala
This fixes the remounting issue I've been having by letting React properly track components. In testing, this only really works if the component function is defined with `val` instead of `def`. Fortunately most places already use `val` to define components.
It should also improve performance slightly overall as this is a change for _all_ components using `ReactFnProps` that results in less rerendering/remounting of components. 
Additionally, the devtools now show component names, which is very useful! It includes the package name, which I personally like as it immediately shows what is a scala.js component.
This change is _source_ compatible, but not _binary_ compatible because of the new `using` param! Downstream libs need to upgrade first before applications like explore can use it. …
> Set displayName for ReactFnProps components

- build.sbt
- grid-layout-demo/src/main/scala/lucuma/react/gridlayout/Demo.scala
- grid-layout/src/main/scala/lucuma/react/gridlayout/ReactGridLayout.scala
- grid-layout/src/main/scala/lucuma/react/gridlayout/ResponsiveReactGridLayout.scala
- grid-layout/src/main/scala/lucuma/react/gridlayout/package.scala
- resizable-demo/src/main/scala/lucuma/react/draggable/demo/Demo.scala
- resizable/src/main/scala/lucuma/react/resizable/Resizable.scala
Changes the `@JSImport`'s to use `@JSImport.Default` and then call the import needed from the object.
Importing named imports doesn't work great for commonJS libraries and causes issues with Vite, because the import is transformed to `import * as $module from 'module'` and then the named import is accessed as `$module.myImport`.
> Use default imports for resizable and grid-layout

- build.sbt
- common/src/main/scala/lucuma/react/common/scalaComponents.scala
Logic for auto-setting `displayName` was moved to `scalajs-react`.
> Bump scalajs-react

- common/src/main/scala/lucuma/react/common/style/package.scala
- prime-react-demo/src/main/scala/lucuma/react/table/demo/DemoControlsPanel.scala
- prime-react/src/main/scala/lucuma/react/primereact/Tooltip.scala
- prime-react/src/main/scala/lucuma/react/primereact/TooltipOptions.scala
- prime-react/src/main/scala/lucuma/react/primereact/tooltip/package.scala
Implement `Tooltip` component from PrimeReact, which allows attaching tooltips to HTML tags.
Usage, as shown on demo:
``` scala
val tooltipTarget = Css("tooltip-target")
React.Fragment(
Tooltip(targetCss = tooltipTarget, content = "I am a tooltip"),
<.span(tooltipTarget, "I am a <span>. Hover over me to see a tooltip."),
<.span(
tooltipTarget, "I am another <span>. Hover over me to see a tooltip too."
).withTooltipOptions(
content = "I'm another tooltip!",
position = Tooltip.Position.Bottom
)
)
```
> Tooltip component

- build.sbt
- prime-react-demo/src/main/scala/lucuma/react/table/demo/DemoControlsPanel.scala
- prime-react/src/main/scala/lucuma/react/primereact/Tooltip.scala
- prime-react/src/main/scala/lucuma/react/primereact/tooltip/package.scala
Turns out that the `content` property had to be a `String`.
This PR fixes that and adds a `Tooltip.Fragment` alternative that renders a `Tooltip` and a passed `HTMLElement` as a `React.Fragment`. This can also be invoked as `<HTMLElement>.withTooltip(<options>...)`.
> Better tooltip API and shorthands

- .github/workflows/ci.yml
- build.sbt
One of my current regrets about sbt-typelevel is that this key is badly named and I think has the wrong default.
https://github.com/typelevel/sbt-typelevel/blob/86874af1c69e80525bef1bfe4678ff29ddce5fe0/ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala#L237-L238
> Treat `project` as disjoint axis in CI matrix

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
This is key to ensure unnecessary remounts when using virtualization. (See what I did there?)
> Add missing key in table renderer

- build.sbt
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
- tanstack-table/src/main/scala/lucuma/react/table/props.scala
The subcomponent functionality was a hack, and we don't really use it. We use better mechanisms when we want to render a row with added information.
> Remove subcomponents for table rows

- build.sbt
- tanstack-table-demo/src/main/scala/lucuma/react/table/demo/Table3.scala
- tanstack-table/src/main/scala/lucuma/react/table/Cell.scala
- tanstack-table/src/main/scala/lucuma/react/table/CellContext.scala
- tanstack-table/src/main/scala/lucuma/react/table/Column.scala
- tanstack-table/src/main/scala/lucuma/react/table/ColumnDef.scala
- tanstack-table/src/main/scala/lucuma/react/table/ColumnPinningPosition.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
- tanstack-table/src/main/scala/lucuma/react/table/Header.scala
- tanstack-table/src/main/scala/lucuma/react/table/HeaderContext.scala
- tanstack-table/src/main/scala/lucuma/react/table/HeaderGroup.scala
- tanstack-table/src/main/scala/lucuma/react/table/HooksApiExt.scala
- tanstack-table/src/main/scala/lucuma/react/table/Row.scala
- tanstack-table/src/main/scala/lucuma/react/table/RowModel.scala
- tanstack-table/src/main/scala/lucuma/react/table/Table.scala
- tanstack-table/src/main/scala/lucuma/react/table/TableHook.scala
- tanstack-table/src/main/scala/lucuma/react/table/TableOptions.scala
- tanstack-table/src/main/scala/lucuma/react/table/facade/ColumnDefJS.scala
- tanstack-table/src/main/scala/lucuma/react/table/facade/TableOptionsJS.scala
- tanstack-table/src/main/scala/lucuma/react/table/package.scala
- tanstack-table/src/main/scala/lucuma/react/table/props.scala
The previous version of the facade exposed some `raw` types.
The new version only exposes Scala types, which have now been type-parameterized with table meta (`TM`) and column meta (`CM`). These allow passing data to cell renderers without redefining the columns, which caused all components to remount.
> react-table full Scala facade, with meta

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTable.scala
- tanstack-table/src/main/scala/lucuma/react/table/props.scala
We now create the ref for the resizer using `useRefToVdom`. This aligns the type for the table renderer.
> Ref types for tables matching the new resizer

- build.sbt
- tanstack-table/src/main/scala/lucuma/react/table/UndefinedPriority.scala
- tanstack-table/src/main/scala/lucuma/react/table/facade/package.scala
Turns out `react-table` implemented `First` and `Last` options in v8.16.0. We don't have to do it manually anymore.
> Update UndefinedPriorityJs for table

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
The virtualization padders didn't account for hidden columns.
> Fix virtualizer padder colSpan

- build.sbt
- tanstack-table-demo/src/main/scala/lucuma/react/table/demo/Table1.scala
- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
Table footers usually contain data rather than headings.
> <td> in table footers

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
Sometimes we don't have footers defined in columns but we do have a general footer in the `footerMod` parameter. When this happens, we have to render the footer.
> Render table footers when mod defined

- beautiful-dnd/src/main/scala/lucuma/react/beautifuldnd/DragDropContext.scala
- beautiful-dnd/src/main/scala/lucuma/react/beautifuldnd/Draggable.scala
- beautiful-dnd/src/main/scala/lucuma/react/beautifuldnd/Droppable.scala
- package-lock.json
- package.json
Phase out the unmaintained `rect-beautiful-dnd` library in favor of `pragmatic-drag-and-drop`, which provides a compatibility layer. The facade remains unchanged.
Eventually, we can fully migrate to the new library, but for now we can switch to a maintained library with zero changes in our code.
> Adopt pragmatic drag and drop through migration library

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
In the HTML table renderer, the defined column width was only applied to the header. This usually works, except if we decide to hide the header.
This PR applies the column width explicitly to every cell, including the footer.
> Tables: apply column width throughout

- tanstack-table/src/main/scala/lucuma/react/table/HTMLTableRenderer.scala
The last PR introduced a bug where it was no longer possible to render custom widths for table cells. In particular, we use this for the expanded rows in the sequence in observe: the expanded row is actually a cell with full width and tweaked positioning.
This PR fixes the issue by applying customizations after the column width.
> Apply table cell width before custom mods

- build.sbt
- prime-react/src/main/scala/lucuma/react/primereact/package.scala
- resize-detector/src/main/scala/lucuma/react/resizeDetector/hooks.scala
Only resizer facade has been migrated so far, mostly as proof-of-concept.
> Migrate to monadic hooks

- build.sbt
- common/src/main/scala/lucuma/react/common/scalaComponents.scala
- hotkeys-hooks/src/main/scala/lucuma/react/hotkeys/hooks.scala
- resize-detector-demo/src/main/scala/lucuma/react/resizeDetector/demo/HookDemo.scala
- resize-detector/src/main/scala/lucuma/react/resizeDetector/hooks.scala
Implements a more compact DSL for defining components:
```scala
case class MyComponent(initial: Int) extends ReactFnProps(MyComponent)
object MyComponent extends ReactFnComponent[MyComponent](props =>
for
s <- useState(props.initial)
yield
<.div(
s.value,
<.button(^.onClick --> s.modState(_ + 1), "Inc")
)
)
```
The `useResizeDetector` demo has been migrated to this style for reference.
This is now possible since hook invocations are inside the render function.
There are also `ReactFnComponentWithChildren`, `ReactComponentForwardRef` and `ReactComponentForwardRefWithChildren` variants.
Also, fixes invocation of `useResizeDetector` monadic style without parameters.
> Enable compact component definition, fix useResize

- prime-react/src/main/scala/lucuma/react/primereact/TooltipOptions.scala
It seems like we commonly just want to specify the position of the tooltip. This makes that simpler.
> Helper values for common TooltipOptions.

- tanstack-table-demo/src/main/scala/lucuma/react/table/demo/Table1.scala
- tanstack-table/src/main/scala/lucuma/react/table/TableOptions.scala
- tanstack-table/src/main/scala/lucuma/react/table/package.scala
To avoid being wasteful, we should only chain the row models that are actually used by the table. See https://tanstack.com/table/v8/docs/guide/row-models.
Note that this could potentially be a breaking change in some tables, although it's very unlikely. Eg: Sorting would be disabled in tables where we didn't set ANY of the sorting properties.
> Avoid computing unnecessary row models in tables
